FROM docker.io/ubuntu/bind9

COPY db.rpz named.conf.local named.conf.options /etc/bind/

RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean

HEALTHCHECK --interval=1s --timeout=3s \
  CMD nc -z localhost 53 || exit 1
