# Copyright 2021 The forwarder Authors. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

---
run:
  timeout: 5m
  build-tags:
    - e2e
  skip-files:
    - httpbin/httpbin.go
    - middleware/delegator.go
    - utils/cobrautil/templates
    - utils/cobrautil/term
    - internal/martian
  silent: true

linters:
  enable-all: true
  disable:
    - contextcheck
    - cyclop
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - gochecknoinits
    - godox
    - goerr113
    - gomnd
    - gomoddirectives
    - maligned
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  fast: false

linters-settings:
  errcheck:
    check-blank: true
  funlen:
    lines: 100
  gocognit:
    min-complexity: 40
  gocyclo:
    min-complexity: 40
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  lll:
    line-length: 180
  nestif:
    min-complexity: 6
  goheader:
    values:
      regexp:
        year: "2022|2023"
    template-path: .go-header-template.yml

issues:
  exclude:
    - "Error return value of `cmd.MarkFlag.+` is not checked"
    - "Error return value of `net.SplitHostPort` is not checked"
    - "Error return value of `w.Write` is not checked"
    - "Function 'RunE' has too many statements"
    - "Function 'RunE' is too long"
    - "Temporary has been deprecated since Go 1.18 because it shouldn't be used"
    - "`nop.+` is unused"
    - "can be `expvar.Var`"
    - "can be `fmt.Stringer`"
    - "missing cases in switch of type Scheme: TunnelScheme"
    - "returns interface \\(github.com/dop251/goja\\.Value\\)"
    - "returns interface \\(github.com/saucelabs/forwarder/internal/martian\\.(Request|Response)+Modifier\\)"
    - "shadow of imported from 'github.com/saucelabs/forwarder/log' package 'log'"
    - "string `https?` has \\d+ occurrences"
  exclude-rules:
    - path: cmd/forwarder/version/version.go
      linters:
        - gochecknoglobals

    - path: _test\.go
      linters:
        - bodyclose
        - funlen
        - gochecknoglobals
        - gocognit
        - gomnd
        - gosec
        - noctx
        - paralleltest
        - testpackage

    - path: e2e/
      linters:
        - gochecknoglobals
        - prealloc
        - nakedret
        - nosprintfhostport

    - path: internal/version/version.go
      linters:
        - gochecknoglobals

    - linters:
        - thelper
      source: "configure: func\\(t \\*testing.T"

    - linters:
        - gochecknoglobals
      source: "(nil)"

    - linters:
        - gochecknoglobals
      source: "Default"

    - linters:
        - gocritic
      source: "// output:"

    - linters:
        - golint
      source: 'import _ "embed"'

    - linters:
        - lll
      source: "//nolint:"

    - linters:
        - lll
      source: "json:"

    - linters:
        - nosnakecase
      source: "func Example"

    - linters:
        - gomnd
      source: "Priority:"

    - path: utils/osdns/
      linters:
        - goheader
