version: "2"
run:
  build-tags:
    - e2e
  tests: true
linters:
  default: none
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - mock_.*\\.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
    - gofmt
  exclusions:
    generated: lax
    paths:
      - mock_.*\\.go
      - third_party$
      - builtin$
      - examples$
