# Copyright 2021 The forwarder Authors. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

---
run:
  timeout: 5m
  build-tags:
    - e2e
  skip-files:
    - middleware/delegator.go
    - utils/cobrautil/templates
    - utils/cobrautil/term
    - sizesuffix
  silent: true

linters:
  enable-all: true
  disable:
    - bodyclose
    - contextcheck
    - cyclop
    - deadcode
    - depguard
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - golint
    - gomnd
    - gomoddirectives
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - scopelint
    - structcheck
    - tagliatelle
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl
  fast: false

linters-settings:
  errcheck:
    check-blank: true
  funlen:
    lines: 160
    statements: 75
  gocognit:
    min-complexity: 50
  gocyclo:
    min-complexity: 40
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  lll:
    line-length: 180
  nestif:
    min-complexity: 11
  goheader:
    values:
      regexp:
        year: "2022|2023"
    template-path: .go-header-template.yml

issues:
  exclude:
    - "Error return value of `cmd.MarkFlag.+` is not checked"
    - "Error return value of `net.SplitHostPort` is not checked"
    - "Error return value of `w.Write` is not checked"
    - "Limiter.WaitN` is not checked"
    - "Function 'runE' has too many statements"
    - "Function 'runE' is too long"
    - "Temporary has been deprecated since Go 1.18 because it shouldn't be used"
    - "`nop.+` is unused"
    - "can be `expvar.Var`"
    - "can be `fmt.Stringer`"
    - "missing cases in switch of type Scheme: TunnelScheme"
    - "shadow of imported from 'github.com/saucelabs/forwarder/log' package 'log'"
    - "string `https?` has \\d+ occurrences"
    - "importShadow: shadow of imported package 'url'"
    - "commentedOutCode: may want to remove commented-out code"
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - errcheck
        - funlen
        - gocognit
        - gomnd
        - gosec
        - noctx
        - paralleltest
        - testpackage

    - path: e2e/
      linters:
        - prealloc
        - nakedret
        - nosprintfhostport

    - path: e2e/run.go
      linters:
        - forbidigo
      text: use of `fmt.Print

    - path: internal/martian
      linters:
        - goheader
        - errcheck
        - gosec

    - path: internal/martian/h2/testing
      linters:
        - forbidigo
      text: use of `fmt.Print

    - linters:
        - thelper
      source: "configure: func\\(t \\*testing.T"

    - linters:
        - gocritic
      source: "// output:"

    - linters:
        - golint
      source: 'import _ "embed"'

    - linters:
        - lll
      source: "//nolint:"

    - linters:
        - lll
      source: "json:"

    - linters:
        - nosnakecase
      source: "func Example"

    - path: utils/osdns/
      linters:
        - goheader
