# Copyright 2021 The forwarder Authors. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

---
run:
  timeout: 1m
  skip-files:
    - internal/*
  silent: true

linters:
  enable-all: true
  disable:
    - wrapcheck
    - testpackage
    - gochecknoglobals
    - exhaustivestruct
    - exhaustruct
    - paralleltest
    - godox
    - cyclop
    - tagliatelle
    - goerr113
    - varnamelen
  fast: false

linters-settings:
  gocognit:
    min-complexity: 40

  funlen:
    lines: 220
    statements: 75

  nestif:
    min-complexity: 8

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoinits
        - gomnd
        - forbidigo
        - lll

    - path: example_test.go
      linters:
        - lll

    - path: internal/http/
      linters:
        - unparam
        - nlreturn

    - path: _test\.go
      linters:
        - scopelint
        - wsl
        - nlreturn
        - funlen
        - dupl
        - gocognit

    - linters:
        - lll
      source: "json:"
