# Copyright 2021 The forwarder Authors. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

---
run:
  timeout: 5m
  skip-files:
    - internal/*
  silent: true

linters:
  enable-all: true
  disable:
    - contextcheck
    - cyclop
    - exhaustivestruct
    - exhaustruct
    - godox
    - goerr113
    - maligned
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  fast: false

linters-settings:
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 40
  gocyclo:
    min-complexity: 40
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  gomnd:
    ignored-numbers: [0, 1, 5, 10, 30, 50, 90, 100]
  lll:
    line-length: 180
  nestif:
    min-complexity: 6

issues:
  exclude:
    - "can be `fmt.Stringer`"
    - "string `https?` has \\d+ occurrences"

  exclude-rules:
    - path: cmd/forwarder/version/version.go
      linters:
        - gochecknoglobals

    - path: _test\.go
      linters:
        - funlen
        - paralleltest
        - testpackage

    - path: example_test\.go
      linters:
        - errcheck
        - gosec

    - linters:
        - gochecknoglobals
      source: "(nil)"

    - linters:
        - gocritic
      source: "// output:"

    - linters:
        - lll
      source: "//nolint:"

    - linters:
        - lll
      source: "json:"

    - linters:
        - nosnakecase
      source: "func Example"

