# Copyright 2021 The forwarder Authors. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

---
run:
  timeout: 5m
  skip-files:
    - internal/*
  silent: true

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - godox
    - goerr113
    - maligned
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  fast: false

linters-settings:
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 40
  gocyclo:
    min-complexity: 40
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  lll:
    line-length: 180
  nestif:
    min-complexity: 6

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals

    - path: _test\.go
      linters:
        - funlen
        - paralleltest
        - testpackage

    - linters:
        - lll
      source: "json:"

    - linters:
        - gocritic
      source: "// output:"
    - linters:
        - nosnakecase
      source: "func Example"

