project_name: forwarder

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^makefile:'
      - '^testing:'

builds:
  - main: ./cmd/forwarder
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags '-static'
      - -X github.com/saucelabs/forwarder/cmd/forwarder/internal/version/Version={{.Version}}
      - -X github.com/saucelabs/forwarder/cmd/forwarder/internal/version/Time={{.Date}}
      - -X github.com/saucelabs/forwarder/cmd/forwarder/internal/version/Commit={{.Commit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums"
