project_name: forwarder

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^makefile:'
      - '^testing:'

builds:
  - main: ./cmd/forwarder
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags '-static'
      - -X github.com/saucelabs/forwarder/cmd/forwarder/version.buildCommit={{.Commit}}
      - -X github.com/saucelabs/forwarder/cmd/forwarder/version.buildVersion={{.Version}}
      - -X github.com/saucelabs/forwarder/cmd/forwarder/version.buildTime={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums"
