# --- Server options ---

# address <host:port>
#
# Address to listen on. If the host is empty, the server will listen on all
# available interfaces.
#address: localhost:1443

# plain-text <value>
#
# Run in plain-text mode i.e. without TLS.
#plain-text: false

# tls-cert-file <path or base64>
#
# TLS certificate to use if the server protocol is https or h2. 
# 
# Syntax:
# - File: /path/to/file.pac
# - Embed: data:base64,<base64 encoded data>
#tls-cert-file: 

# tls-handshake-timeout <duration>
#
# The maximum amount of time to wait for a TLS handshake before closing
# connection. Zero means no limit.
#tls-handshake-timeout: 0s

# tls-key-file <path or base64>
#
# TLS private key to use if the server protocol is https or h2. 
# 
# Syntax:
# - File: /path/to/file.pac
# - Embed: data:base64,<base64 encoded data>
#tls-key-file: 

# --- Logging options ---

# log-file <path>
#
# Path to the log file, if empty, logs to stdout.
#log-file: 

# log-level <error|info|debug>
#
# Log level.
#log-level: info

