// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package pac

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DIRECT-0]
	_ = x[PROXY-1]
	_ = x[SOCKS-2]
	_ = x[HTTP-3]
	_ = x[HTTPS-4]
	_ = x[SOCKS4-5]
}

const _Mode_name = "DIRECTPROXYSOCKSHTTPHTTPSSOCKS4"

var _Mode_index = [...]uint8{0, 6, 11, 16, 20, 25, 31}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
