{
 "title": "Forwarder",
 "tags": [ "Forwarder" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_namespace", "query": "forwarder" },
   { "name": "job", "label": "job", "query": { "query": "label_values(go_info, job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_info{job=~\"$job\"}, instance)"
    }
   },
   { "name": "labels" },
   { "name": "DS_PROMETHEUS", "query": "Prometheus" }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors Rate per Second",
   "type": "state-timeline",
   "description": "Rate of all logged errors.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(${prom_namespace}_errors_total{job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Round Trip Errors Rate",
   "type": "timeseries",
   "description": "The rate of errors encountered on request round trip. ",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errors / s" } },
   "targets": [
    {
     "expr": "sum by (reason) (rate(${prom_namespace}_proxy_errors_total{job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CONNECT Latency - 2XX Requests ",
   "type": "timeseries",
   "description": "The latency of successful CONNECT requests. ",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(${prom_namespace}_http_request_duration_seconds_bucket{code=~\"2..\", method=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])))",
     "legendFormat": "Connect P100"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(${prom_namespace}_http_request_duration_seconds_bucket{code=~\"2..\", method=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])))",
     "legendFormat": "Connect P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(${prom_namespace}_http_request_duration_seconds_bucket{code=~\"2..\", method=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])))",
     "legendFormat": "Connect P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(${prom_namespace}_http_request_duration_seconds_bucket{code=~\"2..\", method=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])))",
     "legendFormat": "Connect P50"
    }
   ]
  },
  {
   "title": "CONNECT 2XX Requests Rate",
   "type": "timeseries",
   "description": "The rate of successful CONNECT requests. ",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "req / s" } },
   "targets": [
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"2..\", method=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval]))",
     "legendFormat": "Connect 2XX"
    }
   ]
  },
  {
   "title": "CONNECT Non-2XX Requests Rate",
   "type": "timeseries",
   "description": "Non-2XX CONNECT requests rate. ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "req / s" } },
   "targets": [
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"1..\", method=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "Connect 1XX"
    },
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"3..\", method=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "Connect 3XX"
    },
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"4..\", method=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on () vector(0)",
     "legendFormat": "Connect 4XX"
    },
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"5..\", method=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "Connect 5XX"
    }
   ]
  },
  {
   "title": "RoundTrip Latency - 2XX Requests",
   "type": "timeseries",
   "description": "The latency of successful HTTP requests. CONNECT requests not included.\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(${prom_namespace}_http_request_duration_seconds_bucket{code=~\"2..\", method!=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])))",
     "legendFormat": "P100"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(${prom_namespace}_http_request_duration_seconds_bucket{code=~\"2..\", method!=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(${prom_namespace}_http_request_duration_seconds_bucket{code=~\"2..\", method!=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(${prom_namespace}_http_request_duration_seconds_bucket{code=~\"2..\", method!=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "2XX Requests Rate",
   "type": "timeseries",
   "description": "The rate of successful HTTP requests.  CONNECT requests not included.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "req / s" } },
   "targets": [
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"2..\", method!=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval]))",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "Non-2XX Requests Rate",
   "type": "timeseries",
   "description": "Non-2XX HTTP requests rate. CONNECT requests not included.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "req / s" } },
   "targets": [
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"1..\", method!=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "1XX"
    },
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"3..\", method!=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"4..\", method!=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum (rate(${prom_namespace}_http_requests_total{code=~\"5..\", method!=\"CONNECT\", job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])) or on() vector(0)",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "HTTP Requests Size (LE)",
   "type": "heatmap",
   "description": "The size of HTTP requests (less or equal).",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (le) (rate(${prom_namespace}_http_request_size_bytes_bucket{job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Responses Size (LE)",
   "type": "heatmap",
   "description": "The size of HTTP responses (less or equal).",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (rate(${prom_namespace}_http_response_size_bytes_bucket{job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Stack",
   "type": "timeseries",
   "description": "Number of bytes allocated on the stack. ",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{job=~\"$job\", instance=~\"$instance\", $labels}",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "description": "Number of bytes allocated on the heap. ",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\", instance=~\"$instance\", $labels}",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "description": "Number of bytes obtained from system.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~\"$job\", instance=~\"$instance\", $labels}",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Available on Linux and Windows.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(${prom_namespace}_process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Pause duration caused by go garbage collection. ",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\", $labels}[$__rate_interval])",
     "legendFormat": "pause"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "stat",
   "description": "Number of Go Threads. ",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{job=~\"$job\", instance=~\"$instance\", $labels}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of Goroutines.\u0010",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\", instance=~\"$instance\", $labels}",
     "legendFormat": "goroutines"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Build",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${prom_namespace}_version{job=~\"$job\", instance=~\"$instance\", $labels}",
     "legendFormat": "Version={{version}} Time={{time}} Commit={{commit}}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{job=~\"$job\", instance=~\"$instance\", $labels}",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}