baseURL = 'https://opensource.saucelabs.com/forwarder/'
languageCode = 'en-us'
title = 'Forwarder'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

disableKinds = ['taxonomy']

[params]
BookTheme = 'auto'
BookSection = '*'
BookSearch = false
BookPortableLinks = true

BookEditPath = 'edit/main/docs'
BookRepo = 'https://github.com/saucelabs/forwarder'
