baseURL = 'https://opensource.saucelabs.com/forwarder/'
languageCode = 'en-us'
title = 'Forwarder Proxy'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

disableKinds = ['taxonomy']

[menu]
[[menu.after]]
  name = "GitHub"
  url = "https://github.com/saucelabs/forwarder"
  weight = 1000

[params]
BookTheme = 'auto'
BookLogo = 'sl.svg'
BookSection = '*'
BookSearch = false
BookPortableLinks = true

BookEditPath = 'edit/main/docs'
BookRepo = 'https://github.com/saucelabs/forwarder'
