---
name: E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version env variables
        run: |
          cat .version >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Build forwarder container
        run: make update-devel-image

      - name: Generate certificates
        run: make -C e2e/certs certs

      - name: Build test container
        run: make -C e2e update-test-image

      - name: Run e2e test
        run: make -C e2e run-e2e

      - name: Docker Compose file
        if: failure()
        run: cat e2e/compose.yaml

      - name: Docker Logs
        if: failure()
        run: make -C e2e dump-logs
