---
name: Vulnerability check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'go.mod'
      - 'go.sum'

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version env variables
        run: |
          cat .version >> $GITHUB_ENV

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: "${{env.GO_VERSION}}"
          go-package: ./...
